-- AlterTable
ALTER TABLE "Map" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "age" VARCHAR,
ADD COLUMN     "email" VARCHAR,
ADD COLUMN     "name" VARCHAR,
ADD COLUMN     "sex" SMALLINT,
ALTER COLUMN "nickname" DROP NOT NULL;
